### ISSUE TITLE
UI problem 2 

### ISSUE THREAD

**Issue by jamesmunsell** [JamesMunsell83/Whatchama#2]
Slidemenu appearing looks not good, fix as other apps' slidemenu.

**Comment by JurekJasinski** [comment]
I have fixed menu, can you check?

**Comment by jamesmunsell** [comment]
Well, still have problem when slide. See the slide menu again, it's showing as jumping, I think it's not like as other left menus.

**Comment by JurekJasinski** [comment]
I have changed again. let me know it's ok.

**Comment by jamesmunsell** [comment]
Ok, sliding is ok now, but at the menu table, can you fix last separator appearing as not shown?

**Comment by JurekJasinski** [comment]
Just fixed now. Plz check.

**Comment by jamesmunsell** [comment]
Ok looks good now.

**Comment by JurekJasinski** [comment]
Thank you, can we finish project?

**Comment by jamesmunsell** [comment]
OK let's go to upwork.

**Comment by JurekJasinski** [comment]
Great
